// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustTemperature(arg1, arg2) {
  return window['go']['main']['App']['AdjustTemperature'](arg1, arg2);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function TogglePower(arg1) {
  return window['go']['main']['App']['TogglePower'](arg1);
}
