// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AdjustTemperature(arg1:number,arg2:number):Promise<void>;

export function GetDevices():Promise<Array<main.Device>>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function TogglePower(arg1:number):Promise<void>;
